@startuml
skinparam dpi 300

!define AzurePuml https://raw.githubusercontent.com/RicardoNiepel/Azure-PlantUML/release/2020.12.15
!include url AzurePuml/AzureCommon.puml
!include url AzurePuml/Network/AzureVirtualNetwork.puml
!include url AzurePuml/Compute/AzureVirtualMachines.puml
!include url AzurePuml/Storage/AzureStorageAccount.puml
!include url AzurePuml/General/AzureMonitor.puml

title Infraestructura Lógica y Física en Azure

AzureVirtualNetwork("vnet", "TechRetail-VNet", "Red Virtual")
AzureVirtualMachines("vm_dc", "VM-DC", "Controlador de Dominio, DNS, y NAP")
AzureVirtualMachines("vm_iis_sql", "VM-IIS-SQL", "Servidor IIS y SQL")
AzureVirtualMachines("vm_monitor", "VM-Monitor", "Nodo Secundario y Monitorización")
AzureVirtualMachines("vm_cliente", "VM-Cliente", "Cliente Remoto")
AzureMonitor("monitor", "Azure Monitor", "Herramientas de Monitorización")

' Conexiones lógicas'
vnet -[hidden]-> vm_dc
vnet -[hidden]-> vm_iis_sql
vnet -[hidden]-> vm_monitor
vnet -[hidden]-> vm_cliente

' Detalles de configuración'
AzureStorageAccount("storage_account", "Almacenamiento Clúster Witness", "Soporte para el clúster de conmutación por error")
vm_dc --> storage_account : "\\ClusterWitness"

' Seguridad y conexión'
package "Subred Pública" {
  vm_dc
  vm_iis_sql
  vm_monitor
}
package "Subred Cliente" {
  vm_cliente
}

@enduml
